title: SaüSiber
description: SaüSiber Blog
logo: /static/img/avatar.png
about: Sakarya Üniversitesi Siber Güvenlik Topluluğu

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: sausiber-org
google_analytics:

share:
  twitter_username: sausiber
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]


people:
- name: Semih Demirci
  pic: 1
  position: Başkan
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://facebook.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/

- name: Alperen Örsdemir
  pic: 2
  position: Başkan Yardımcısı
  social:
    - title: twitter
      url: https://twitter.com/basakgurbet
    - title: github
      url: https://github.com/gurbetbasakci
    - title: linkedin
      url: https://tr.linkedin.com/in/gurbet-başakçi-048551135

- name: Kadir Arslan
  pic: 3
  position: Siber Güvenlik Kümelenmesi Temsilcisi
  social:
    - title: twitter
      url: https://twitter.com/kadars_
    - title: github
      url: https://github.com/KadirArslan
    - title: linkedin
      url: https://www.linkedin.com/in/kadirarslan1/

- name: Cahit Tulum
  pic: 4
  position: Sekreter
  social:
    - title: twitter
      url: https://twitter.com/cahittulum
    - title: github
      url: https://github.com/Imperiosx
    - title: linkedin
      url: https://www.linkedin.com/in/cahit-tulum-28b185126

- name: Özgür Algül
  pic: 5
  position: Üye
  social:
    - title: twitter
      url: https://twitter.com/ozguralgul44
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://www.linkedin.com/in/özgür-algül-1b9761152

- name: Hasan Tenk
  pic: 6
  position: Üye
  social:
    - title: twitter
      url: https://twitter.com/tnk_hasan
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://www.linkedin.com/in/hasan-tenk-78aa60150

- name: Ertuğrul Karababa
  pic: 7
  position: Üye
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://linkedin.com/in/ertuğrul-karababa-a96926102

- name: Züleyha Müzennet
  pic: 8
  position: Üye
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: www.linkedin.com/

- name: Gurbet Başakçi
  pic: 9
  position: Üye
  social:
    - title: twitter
      url: https://twitter.com/gurbetbasakci
    - title: github
      url: https://github.com/gurbetbasakci
    - title: linkedin
      url: https://www.linkedin.com/in/gurbet-başakçi-048551135

- name: Mert Derebaşı
  pic: 10
  position: Üye
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://www.linkedin.com/

- name: Hakan İlbiz
  pic: 11
  position: Üye
  social:
    - title: github
      url: https://github.com/pioneerhfy
    - title: linkedin
      url: https://www.linkedin.com/in/hakan-ilbiz-769191131?trk=nav_responsive_tab_profile_pic

- name: Umut Tosun
  pic: 12
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/umuttosun_
    - title: github
      url: https://github.com/umuttosun
    - title: linkedin
      url: https://github.com/umuttosun

- name: Ömer Günal
  pic: 13
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/ogunal00
    - title: github
      url: https://github.com/omergunal
    - title: linkedin
      url: https://www.linkedin.com/in/%C3%B6mer-g%C3%BCnal-677271130/
