title: SaüSiber
description: SaüSiber Blog
logo: /static/img/avatar.png
about: Sakarya Üniversitesi Siber Güvenlik Topluluğu

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: sausiber-org
google_analytics:

share:
  twitter_username: sausiber
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]


people:
- name: Ahmet Derviş
  pic: 1
  position: Başkan
  social:
    - title: twitter
      url: https://twitter.com/adrvs42
    - title: github
      url: https://github.com/adervis3
    - title: linkedin
      url: https://tr.linkedin.com/in/ahmet-dervis

- name: Semih Demirci
  pic: 2
  position: Başkan Yardımcısı
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://facebook.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/

- name: Gurbet Başakçi
  pic: 3
  position: Sekreter
  social:
    - title: twitter
      url: https://twitter.com/basakgurbet
    - title: github
      url: https://github.com/gurbetbasakci
    - title: linkedin
      url: https://tr.linkedin.com/in/gurbet-başakçi-048551135

- name: Mert Derebaşı
  pic: 4
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/MertHasanD
    - title: github
      url: https://github.com/merthasanderebasi
    - title: linkedin
      url: www.linkedin.com/in/merthasanderebasi

- name: Hakan İlbiz
  pic: 5
  position: Üye
  social:
    - title: github
      url: https://github.com/pioneerhfy
    - title: linkedin
      url: https://www.linkedin.com/in/hakan-ilbiz-769191131?trk=nav_responsive_tab_profile_pic

- name: Ömer Günal
  pic: 6
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/ogunal00
    - title: github
      url: https://github.com/omergunal
    - title: linkedin
      url: https://www.linkedin.com/in/%C3%B6mer-g%C3%BCnal-677271130/

- name: Umut Tosun
  pic: 7
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/umuttosun_
    - title: github
      url: https://github.com/umuttosun
    - title: linkedin
      url: https://github.com/umuttosun

- name: Ulaş Fırat Özdemir
  pic: 8
  position: Üye
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #
