permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8


title:               SaüSiber
description:         "Sakarya Üniversitesi Siber Güvenlik Topluluğu"
url: http://sausiber.org/
baseurl: ""
favicon: "favicon.png"
urlimg: http://sausiber.org/images/
markdown: kramdown
kramdown:
  math_engine: mathjax

paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
future:      true


syntax_highlighter: rouge
input: GFM

gems:
  - github-pages
  - font-awesome-sass
  - jekyll-redirect-from
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com/SauSiber

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]


people:
- name: Ahmet Derviş
  pic: 1
  position: Başkan
  social:
    - title: twitter
      url: https://twitter.com/adrvs42
    - title: github
      url: https://github.com/adervis3
    - title: linkedin
      url: https://tr.linkedin.com/in/ahmet-dervis

- name: Semih Demirci
  pic: 2
  position: Başkan Yardımcısı
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://facebook.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/

- name: Gurbet Başakçı
  pic: 3
  position: Sekreter
  social:
    - title: twitter
      url: https://twitter.com/basakgurbet
    - title: github
      url: https://github.com/gurbetbasakci
    - title: linkedin
      url: https://tr.linkedin.com/in/gurbet-başakçi-048551135

- name: Mert Derebaşı
  pic: 4
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/MertHasanD
    - title: github
      url: https://github.com/merthasanderebasi
    - title: linkedin
      url: www.linkedin.com/in/merthasanderebasi

- name: Hakan İlbiz
  pic: 5
  position: Üye
  social:
    - title: github
      url: https://github.com/pioneerhfy
    - title: linkedin
      url: https://www.linkedin.com/in/hakan-ilbiz-769191131?trk=nav_responsive_tab_profile_pic

- name: Ömer Günal
  pic: 6
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/ogunal00
    - title: github
      url: https://github.com/omergunal
    - title: linkedin
      url: https://www.linkedin.com/in/%C3%B6mer-g%C3%BCnal-677271130/

- name: Umut Tosun
  pic: 7
  position:  Üye
  social:
    - title: twitter
      url: https://twitter.com/umuttosun_
    - title: github
      url: https://github.com/umuttosun
    - title: linkedin
      url: https://github.com/umuttosun

- name: Ulaş Fırat Özdemir
  pic: 8
  position: Üye
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: linkedin
      url: #


old:
- name: Fatih Erdoğan
  pic: 1
  social:
    - title: twitter
      url: https://twitter.com/FeCassie
    - title: github
      url: https://github.com/FeCassie
    - title: linkedin
      url: https://tr.linkedin.com/in/fatiherdogan1
- name: Şevket Kaan Bostancı
  pic: 2
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Uygar Köroğlu
  pic: 3
  social:
    - title: twitter
      url: https://twitter.com/uygarkoroglu
    - title: github
      url: https://github.com/uygarkoroglu
    - title: linkedin
      url: https://tr.linkedin.com/in/uygarkoroglu
- name: Nisa Türkmen
  pic: 4
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Mürüvet Uslu
  pic: 5
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Umut Ergin
  pic: 6
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Elif ikbal Yöntem
  pic: 7
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Oğulcan Gürçağlar
  pic: 8
  social:
    - title: twitter
      url: https://twitter.com/
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Samet Sazak
  pic: 9
  social:
    - title: twitter
      url: https://twitter.com/samet_sazak
    - title: github
      url: https://github.com/
    - title: linkedin
      url: https://tr.linkedin.com/in/
- name: Meryem Kaplan
  pic: 10
  social:
    - title: twitter
      url: https://twitter.com/meryemkpln
    - title: github
      url: https://github.com/meryemkaplan



# About/contact
author:
  name:              SaüSiber
  url:               https://twitter.com/sausiber
  avatar:         avatar.png
  email:          sausiber@gmail.com           

# Owner/author information
owner:
  name:           SaüSiber
  avatar:         avatar.png
  email:          sausiber@gmail.com 
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        SauSiber 
  facebook:       SauSiber
  github:         sausiber
  #stackexchange:  
  #linkedin:       
  #instagram:      
  #flickr:
  #tumblr:  
  #google_plus:    
  # orcid and google scholar IDs are different than standard username.
  #orcid: 
  #gscholar: 

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Ana Sayfa
    url: 
  - title: <i class="iconside iconm-quill"></i> Blog
    url: blog/
  - title: <i class="fa fa-group"></i> Biz
    url: ekip/
  - title: <i class="fa fa-archive"></i> Eski Üyelerimiz
    url: eski/
  - title: <i class="iconside iconm-user"></i> Hakkımızda
    url: hakkimizda/
  - title: <i class="iconside iconm-envelop"></i> İletişim
    url: iletisim/
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml

# Google Custom Search:
google_search: SauSiber
twitter_widget_id: <a href="https://twitter.com/SauSiber">Tweets by SauSiber</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

